import { Menu } from "@/common/components/Menu";
import "../styles/global.scss";
import { roboto } from "../styles/font";

export const metadata = {
  title: "Layout Next.js title",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <Menu />
        <main className="main-container">{children}</main>
      </body>
    </html>
  );
}
