import { Menu } from "@/common/components/Menu";

export const metadata = {
  title: ' Layout Next.js title',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Menu />
      {children}
      </body>
    </html>
  )
}
